version: '3.8'
services:
  judger:
    build: .
    volumes:
      - ./submissions:/noj-350/submissions:ro
      - ./testcase:/noj-350/testcase:ro
      - ./judge.py:/noj-350/judge.py
    command:
      - judge-all
